# Generated by Django 5.1.5 on 2025-01-24 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('f', models.CharField(max_length=10)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budgets.budget')),
                ('category', models.ManyToManyField(related_name='transactions', to='budgets.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
