# Generated by Django 5.1.5 on 2025-01-24 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.DecimalField(db_default=0.0, decimal_places=2, max_digits=8)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('repeat_frequency', models.DurationField()),
                ('duration', models.IntegerField()),
                ('duration_unit', models.CharField(choices=[('Y', 'Year'), ('M', 'Month'), ('D', 'Day'), ('h', 'Hour'), ('m', 'Minute'), ('s', 'Second'), ('DOW', 'Day of the week'), ('DOY', 'Day of the year')], default='D', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
