# Generated by Django 5.1.5 on 2025-01-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='repeat_frequency',
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='end date'),
        ),
    ]
