# Generated by Django 5.1.5 on 2025-01-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_recurringtransaction_repeat_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='end_date',
        ),
    ]
