# Generated by Django 5.1.5 on 2025-01-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_recurringtransaction_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='is_indefinate',
            field=models.BooleanField(default=True),
        ),
    ]
