# Generated by Django 5.1.5 on 2025-01-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_purchase_rename_recurringtransaction_recurringbill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecurringBill',
            new_name='Bill',
        ),
    ]
